"""Stub stage runners for story 9.

These run briefly, mutate the store to simulate the stage having completed,
and return. Swapping them for real subprocess wrappers around
`force_align.py`, `gen_keyframes.py`, etc., is a localised change later.

Contract per stage: runs against the given song + its scenes; on success the
relevant DB fields are populated. No external calls are made.
"""

from __future__ import annotations

import asyncio
import json
import time
from pathlib import Path

from ..store import connection


async def stub_transcribe(song_id: int, *, db_path: Path) -> None:
    """Mark the scenes as existing. Real impl would run WhisperX and populate
    scenes from the aligned output — for the stub we treat the pre-existing
    import as sufficient. No-op + short sleep so the UI shows progress."""
    await asyncio.sleep(0.1)


async def stub_world_brief(song_id: int, *, db_path: Path) -> None:
    await asyncio.sleep(0.1)
    with connection(db_path) as conn:
        conn.execute(
            "UPDATE songs SET world_brief = COALESCE(world_brief, ?), updated_at = ? WHERE id = ?",
            ("(stub) Song world description generated by the editor.",
             time.time(), song_id),
        )


async def stub_storyboard(song_id: int, *, db_path: Path) -> None:
    await asyncio.sleep(0.1)
    now = time.time()
    with connection(db_path) as conn:
        conn.execute(
            "UPDATE songs SET sequence_arc = COALESCE(sequence_arc, ?), updated_at = ? WHERE id = ?",
            ("(stub) The narrator moves through the song.", now, song_id),
        )
        # Fill any missing beat/camera_intent/subject_focus with plausible defaults
        conn.execute("""
            UPDATE scenes SET
                beat = COALESCE(beat, '(stub) narrative beat'),
                camera_intent = COALESCE(camera_intent, 'static hold'),
                subject_focus = COALESCE(subject_focus, 'the narrator'),
                updated_at = ?
            WHERE song_id = ?
        """, (now, song_id))


async def stub_image_prompts(song_id: int, *, db_path: Path) -> None:
    await asyncio.sleep(0.2)
    now = time.time()
    with connection(db_path) as conn:
        conn.execute("""
            UPDATE scenes SET
                image_prompt = CASE
                    WHEN prompt_is_user_authored = 1 THEN image_prompt
                    ELSE COALESCE(image_prompt, '(stub) per-scene image prompt')
                END,
                updated_at = ?
            WHERE song_id = ?
        """, (now, song_id))


async def stub_keyframes(song_id: int, *, db_path: Path, source_run_id: int) -> None:
    """Create a placeholder keyframe take for every scene that doesn't yet have one."""
    await asyncio.sleep(0.3)
    now = time.time()
    with connection(db_path) as conn:
        scenes = conn.execute(
            "SELECT id, scene_index, image_prompt, selected_keyframe_take_id "
            "FROM scenes WHERE song_id = ? ORDER BY scene_index",
            (song_id,),
        ).fetchall()
        for s in scenes:
            if s["selected_keyframe_take_id"] is not None:
                continue
            asset_path = f"(stub) keyframe for scene {s['scene_index']} run {source_run_id}"
            cur = conn.execute(
                "INSERT INTO takes (scene_id, artefact_kind, asset_path, "
                "prompt_snapshot, created_by, source_run_id, created_at) "
                "VALUES (?, 'keyframe', ?, ?, 'editor', ?, ?)",
                (s["id"], asset_path, s["image_prompt"], source_run_id, now),
            )
            conn.execute(
                "UPDATE scenes SET selected_keyframe_take_id = ?, updated_at = ? "
                "WHERE id = ? AND selection_pinned = 0",
                (cur.lastrowid, now, s["id"]),
            )


async def stub_final_render(song_id: int, *, db_path: Path, source_run_id: int) -> None:
    """Story 10 stub: ensure every scene has a clip take, then emit a single
    finished_videos row pointing at a placeholder path."""
    await asyncio.sleep(0.2)
    now = time.time()
    with connection(db_path) as conn:
        song = conn.execute("SELECT quality_mode FROM songs WHERE id = ?",
                            (song_id,)).fetchone()
        scenes = conn.execute(
            "SELECT id, scene_index, selected_clip_take_id FROM scenes "
            "WHERE song_id = ? ORDER BY scene_index", (song_id,),
        ).fetchall()
        gap_count = 0
        for s in scenes:
            if s["selected_clip_take_id"] is not None:
                continue
            # Create a placeholder clip take so the scene is "covered"
            path = f"(stub) clip for scene {s['scene_index']} run {source_run_id}"
            cur = conn.execute(
                "INSERT INTO takes (scene_id, artefact_kind, asset_path, "
                "source_run_id, quality_mode, created_by, created_at) "
                "VALUES (?, 'clip', ?, ?, ?, 'editor', ?)",
                (s["id"], path, source_run_id, song["quality_mode"], now),
            )
            conn.execute(
                "UPDATE scenes SET selected_clip_take_id = ?, updated_at = ? "
                "WHERE id = ? AND selection_pinned = 0",
                (cur.lastrowid, now, s["id"]),
            )
            gap_count += 1

        # Write the finished video row
        final_path = f"(stub) editor/data/finals/song{song_id}_run{source_run_id}.mp4"
        conn.execute("""
            INSERT INTO finished_videos
                (song_id, file_path, quality_mode, scene_count, gap_count,
                 final_run_id, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            song_id, final_path, song["quality_mode"],
            len(scenes), gap_count, source_run_id, now,
        ))
